CREATE TABLE positions (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id          BIGINT NOT NULL,
    coin                VARCHAR(20) NOT NULL,
    state               VARCHAR(30) NOT NULL,
    upbit_qty           DECIMAL(20,8) NOT NULL,
    bybit_qty           DECIMAL(20,8) NOT NULL,
    upbit_entry_price   DECIMAL(20,8),
    bybit_entry_price   DECIMAL(20,8),
    upbit_order_id      VARCHAR(100),
    bybit_order_id      VARCHAR(100),
    entry_spread_pct    DOUBLE,
    entry_z_score       DOUBLE,
    entry_usd_krw       DOUBLE,
    opened_at           DATETIME(3),
    closed_at           DATETIME(3),
    realized_pnl        DECIMAL(20,8),
    exit_upbit_order_id VARCHAR(100),
    exit_bybit_order_id VARCHAR(100),
    client_order_id     VARCHAR(100),
    exit_client_order_id VARCHAR(64) NULL,
    in_flight           BOOLEAN DEFAULT FALSE,
    succeeded_leg       VARCHAR(10),
    emergency_attempts  INT DEFAULT 0,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    INDEX idx_session_state (session_id, state),
    INDEX idx_coin_state (coin, state)
);
